"""empty message

Revision ID: ded767e60ea5
Revises: 
Create Date: 2024-09-17 19:41:22.086950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded767e60ea5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriptions', sa.String(length=80), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'stores', ['password'], ['id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('descriptions')

    # ### end Alembic commands ###
